#!/bin/bash

set -eu

juju-log "We've got a db"

source inc/common

if [ -f "$config_file_path" ] || [ -f "$config_db_file_path" ]; then
  juju-log "Drupal is already setup, just silently going away"
  exit 0
fi

database=`relation-get database`
user=`relation-get user`
password=`relation-get password`
host=`relation-get private-address`

if [ -z "$database" ] ; then
  exit 0
fi

# Drupal: Settings.
cp $drupal_path/sites/default/default.settings.php $config_file_path
echo "\n\einclude settings.db.php" >> $config_file_path


# Drupal: 

. hooks/config-changed
. hooks/restart

# Make it publicly visible, once the Drupal service is exposed
open-port 80/tcp