#!/bin/bash

set -eu

juju-log "We've got a db"

source inc/common

if [ -f "$config_file_path" ] || [ -f "$config_db_file_path" ]; then
  juju-log "Drupal is already setup, just silently going away"
  exit 0
fi

host=`relation-get private-address`
database=`relation-get database`
user=`relation-get user`
password=`relation-get password`

if [ -z "$database" ] ; then
  exit 0
fi

# Drupal: Include the new Settings.
echo -e "\ninclude settings.db.php" >> $config_file_path

# Database info.
cp files/charm/drupal/settings.db.php $config_db_file_path

sed -i "s/\${host}/$host/" $config_db_file_path
sed -i "s/\${database}/$database/" $config_db_file_path
sed -i "s/\${user}/$user/" $config_db_file_path
sed -i "s/\${password}/$password/" $config_db_file_path

# Configuring the Salt hash.
(
  cd $drupal_path
  drupal_hash_salt=`drush php-eval "echo drupal_get_hash_salt();"`
  sed -i "s/^\$drupal_hash_salt = \'\'\;/\$drupal_hash_salt = \'$drupal_hash_salt\'\;/" $config_file_path
)

chmod 0644 $config_file_path
chmod 0644 $config_db_file_path
 
juju-log "Resetting permissions"
 
chown -R ubuntu:www-data $project_path

# When project is from an existent Git repository, will try to import the dump form the branch.
if is_project_from_git && [ -f $project_path/databases/$DEPLOY_BRANCH.dump.sql ]; then
  juju-log "Trying to importing MySQL dump in /databases/$DEPLOY_BRANCH.dump.sql"
  (
    cd $drupal_path
    drush sqlc < $project_path/databases/$DEPLOY_BRANCH.dump.sql
  )
  drupal_clear_all_cache
fi

. hooks/restart

# Make it publicly visible, once the Drupal service is exposed
open-port 80/tcp